### ISSUE TITLE
Documentation rework TODO list

### ISSUE THREAD

**Issue by hruotsalainen** [lorabridge2/lorabridge2.github.io#1]
- [x] Update front-page system diagram to indicate automation updates via downlink @hruotsalainen 
- [x] Update front-page logo @hruotsalainen 
- [x] Add LoRaMation under how-to-use @tobiasdam 
- [x] Update how-to-pair under how-to-use @hruotsalainen 
- [x] Update installation @tobiasdam 
- [x] Update hardware @hruotsalainen  and software components @tobiasdam 
- [x] Update troubleshooting @hruotsalainen 
- [x] Add how-to add custom LBNode under development @hruotsalainen 
- [x] Add downlink compression rules under development @hruotsalainen
